language: go
go:
  - 1.9
install:
  - git clone https://github.com/json-c/json-c.git
  - cd json-c
  - sudo apt-get install build-essential swig
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd -
  - go get -t -v ./...
script: 
  - bash ./test.sh
matrix:
  include:
    - language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      script:
        - cd internal/wrappers && make java
after_success:
  - cd .cover && bash <(curl -s https://codecov.io/bash)
