install:
  - git clone https://github.com/json-c/json-c.git
  - cd json-c
  - sudo apt-get install build-essential swig
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd -
  - go get -t -v ./...
matrix:
  include:
    - language: go
      go:
        - 1.9
      script: 
        - bash ./test.sh
    - language: java
      addons:
        apt:
          packages:
            - oracle-java8-installer
      script:
        - cd internal/wrappers && make java
after_success:
  - cd .cover && bash <(curl -s https://codecov.io/bash)
